interface=eth0
except-interface=lo
bind-interfaces
domain-needed
strict-order
bogus-priv
no-negcache
no-resolv
no-hosts
no-poll
no-ping

filter-rr=AAAA
filter-rr=HTTPS

port=3535

user=nobody
group=daemon

max-cache-ttl=64
cache-size=1024
server=127.0.0.1#53

address=/#/127.0.0.1

