user daemon
pidfile /var/run/sniproxy.pid

error_log {
    filename /proc/self/fd/2
    priority notice
}

resolver {
    # nameserver 8.8.8.8
    # nameserver 8.8.4.4 # local dns should be better
    nameserver 127.0.0.1
    mode ipv4_only
}

listener 0.0.0.0:80 {
    proto http
    reuseport yes
    access_log {
        filename /proc/self/fd/1
        priority notice
    }
}

listener 0.0.0.0:443 {
    proto tls
    reuseport yes
    access_log {
        filename /proc/self/fd/1
        priority notice
    }
}

table {
    .* *
}


